### PR TITLE
Use JUL logger instead of System.{out,err}.println

### PR DESCRIPTION
**Pull request by ruke47**

### CODE REVIEW

**Review by nemonik — COMMENTED** [review]
I just saw this... I will merge in a couple of days.

**Comment by gtback** [comment]
@nemonik: Should this get merged in before making a new release (per #13?)

**Comment by nemonik** [comment]
I need to move this to Apache Log4j 2.

**Comment by ruke47** [comment]
Ha! I prefer Log4j2 myself, but I figured that JUL involved fewer dependencies, and wanted to keep the friction as low as possible.

**Pull request merged**
